name: app
networks:
  app:
    driver: bridge
services:
  stub-intra-api:
    container_name: stub-intra-api
    image: app/stub-intra-api:latest
    build:
      dockerfile: Dockerfile
      context: ./stub_intra_api
      tags:
        - app/stub-intra-api:latest
    networks:
      - app
    healthcheck:
      test:
        - CMD
        - wget
        - --no-verbose
        - --spider
        - "http://localhost:8000"
      interval: 60s
      timeout: 5s
      start_period: 2s
      retries: 5
  stub-external-requester:
    container_name: stub-external-requester
    image: app/stub-external-requester:latest
    build:
      dockerfile: Dockerfile
      context: ./stub_external_requester
      tags:
        - app/stub-external-requester:latest
    networks:
      - app
    depends_on:
      stub-intra-api:
        condition: service_healthy
