line_ending: lf
doublestar: true
continue_on_error: false
include: []
exclude: []
gitignore_excludes: false
output_format: default
formatter:
  type: basic
  indent: 2
  include_document_start: false
  retain_line_breaks: false
  retain_line_breaks_single: false
  disallow_anchors: false
  max_line_length: 120
  scan_folded_as_literal: false
  indentless_arrays: false
  drop_merge_tag: false
  pad_line_comments: 1
  trim_trailing_whitespace: true
  eof_newline: true
