# yaml-language-server: $schema=https://json.schemastore.org/github-action.json
name: setup-terraform
description: |
  terraformのセットアップを行う
runs:
  using: composite
  steps:
    - name: source .env.tool-versions
      uses: ./.github/actions/setup/common/source-env-tool-versions
    - name: cache terraform binary
      id: cache_terraform_binary
      uses: actions/cache@v4.1.0
      with:
        path: /usr/local/bin/terraform
        key: "${{ runner.os }}-\
          terraform-\
          binary-\
          cache-\
          ${{ env.TERRAFORM_VERSION }}"
    - name: install terraform
      if: >-
        ${{ steps.cache_terraform_binary.outputs.cache-hit != 'true' }}
      shell: bash
      env:
        TERRAFORM_VERSION: "${{ env.TERRAFORM_VERSION }}"
      run: |
        BINARY_NAME="terraform"; \
        TARGETARCH="$(dpkg --print-architecture)"; \
        RELEASE_FILE_NAME_WO_EXTENSION="${BINARY_NAME}_${TERRAFORM_VERSION}_linux_${TARGETARCH}"; \
        RELEASE_FILE_NAME="${RELEASE_FILE_NAME_WO_EXTENSION}.zip"; \
        wget --progress=dot:giga "https://releases.hashicorp.com/terraform/${TERRAFORM_VERSION}/${RELEASE_FILE_NAME}" \
        && unzip "${RELEASE_FILE_NAME}" \
        && install -v -m 0755 "${BINARY_NAME}" /usr/local/bin
