# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
# ref:
# - https://developer.hashicorp.com/terraform/language/expressions/version-constraints
# - https://developer.hashicorp.com/terraform/language/providers/requirement
terraform {
  required_version = "~> 1.9.7"

  required_providers {
    # !CAUTION: child module for GitHub Provider must add a required_providers for "integrations/github" or it will try and install "hashicorp/github"
    # ref: https://registry.terraform.io/providers/integrations/github/latest/docs
    github = {
      source  = "integrations/github"
      version = "~> 6.3.0"
    }
    local = {
      # ref: https://registry.terraform.io/providers/hashicorp/local/latest/docs
      source  = "hashicorp/local"
      version = "~> 2.5.2"
    }
    null = {
      # ref: https://registry.terraform.io/providers/hashicorp/null/latest/docs
      source  = "hashicorp/null"
      version = "~> 3.2.3"
    }
    random = {
      # ref: https://registry.terraform.io/providers/hashicorp/random/latest/docs
      source  = "hashicorp/random"
      version = "~> 3.6.3"
    }
    external = {
      # ref: https://registry.terraform.io/providers/hashicorp/external/latest/docs
      source  = "hashicorp/external"
      version = "~> 2.3.4"
    }
    assert = {
      # ref: https://registry.terraform.io/providers/hashicorp/assert/latest/docs
      source  = "hashicorp/assert"
      version = "~> 0.14.0"
    }
  }
}
