# eslint-disable yml/block-mapping-colon-indicator-newline
# yaml-language-server: $schema=https://json.schemastore.org/github-action.json
# refs:
# - composite actions:
#   - https://docs.github.com/en/actions/sharing-automations/creating-actions/metadata-syntax-for-github-actions#runs-for-composite-actions
#   - https://docs.github.com/en/actions/sharing-automations/creating-actions/creating-a-composite-action
# - docker.docs - Introduction to GitHub Actions:
#   - https://docs.docker.com/build/ci/github-actions/
# - docker.docs - Configuring your GitHub Actions builder:
#   - https://docs.docker.com/build/ci/github-actions/configure-builder/
# - GitHub Actions starter-workflows:
#   - https://github.com/actions/starter-workflows
# - GitHub Actions starter-workflows - docker-publish.yml:
#   - https://github.com/actions/starter-workflows/blob/main/ci/docker-publish.yml
# - docker build:
#   - https://docs.docker.com/build/
# - docker buildx:
#   - https://github.com/docker/buildx
#   - https://docs.docker.com/build/
#   - https://docs.docker.com/reference/cli/docker/buildx/
# - BuildKit:
#   - https://github.com/moby/buildkit
#   - https://docs.docker.com/build/buildkit/
# - setup-buildx-action:
#   - https://github.com/docker/setup-buildx-action
# requirements:
# - following envs set in .env.tool-versions:
#   - ACTIONS_DOCKER_SETUP_BUILDX_VERSION
#   - DOCKER_BUILDX_VERSION
#   - BUILDKIT_VERSION
name: setup-docker
description: |
  dockerのセットアップを行う
inputs:
  DEBUG:
    description: |
      デバッグモード
    required: false
    default: "false"
runs:
  using: composite
  steps:
    - name: source .env.tool-versions
      uses: ./.github/actions/setup/common/source-env-tool-versions
    - name: setup buildx
      uses:
        "docker/setup-buildx-action@\
        ${{ env.ACTIONS_DOCKER_SETUP_BUILDX_VERSION }}"
      # ref: https://github.com/docker/setup-buildx-action/blob/master/action.yml
      with:
        version: ${{ env.DOCKER_BUILDX_VERSION }}
        driver: docker-container
        driver-opts: "image=moby/buildkit:v${{ env.BUILDKIT_VERSION }}"
        buildkitd-flags: ${{ inputs.DEBUG == 'true' && '--debug' || '' }}
        install: true
        use: true
        cache-binary: true
        cleanup: true
