# eslint-disable yml/block-mapping-colon-indicator-newline
# yaml-language-server: $schema=https://json.schemastore.org/github-action.json
# refs:
# - composite actions:
#   - https://docs.github.com/en/actions/sharing-automations/creating-actions/metadata-syntax-for-github-actions#runs-for-composite-actions
#   - https://docs.github.com/en/actions/sharing-automations/creating-actions/creating-a-composite-action
# requirements:
# - ACTIONS_CONFIGURE_AWS_CREDENTIALS_VERSION set in .env.tool-versions
# - IAM Role created via terraform/terragrunt or bash script:
#   - ./scripts/bash/aws/iam_oidc_provider_and_role_for_github_action.sh
name: setup-aws-credentials
description: |
  setup aws credentials with assume role
inputs:
  AWS_REGION:
    description: |
      AWS region
    required: false
    default: ap-northeast-1
  AWS_ACCOUNT_ID:
    description: |
      AWS Account ID
    required: true
  ASSUME_ROLE_PREFIX:
    description: |
      IAM Role prefix
    required: false
    default: xev-vpp-evems
  ENVIRONMENT:
    description: |
      Environment
    required: false
    default: dev
  ASSUME_ROLE_RESOURCE_NAME_PREFIX:
    description: |
      IAM Role name prefix
    required: false
    default: iamr
  ASSUME_ROLE_RESOURCE_NAME:
    description: |
      IAM Role name prefix
    required: false
    default: github-actions
runs:
  using: composite
  steps:
    - name: source .env.tool-versions
      uses: ./.github/actions/setup/common/source-env-tool-versions
    # ref: https://github.com/aws-actions/configure-aws-credentials
    - name: configure aws credentials
      uses: aws-actions/configure-aws-credentials@v4.0.2
      with:
        aws-region: ${{ inputs.AWS_REGION }}
        role-to-assume:
          "arn:aws:iam::\
          ${{ inputs.AWS_ACCOUNT_ID }}:\
          role/${{ inputs.ASSUME_ROLE_PREFIX || '${SYSTEM}-${SUBSYSTEM}' }}-\
          ${{ inputs.ENVIRONMENT }}-\
          ${{ inputs.ASSUME_ROLE_RESOURCE_NAME_PREFIX }}-\
          ${{ inputs.ASSUME_ROLE_RESOURCE_NAME }}"
        role-session-name: "GitHubActions-${{ github.run_id }}"
