# eslint-disable yml/block-mapping-colon-indicator-newline
# yaml-language-server: $schema=https://json.schemastore.org/github-action.json
# refs:
# - composite actions:
#   - https://docs.github.com/en/actions/sharing-automations/creating-actions/metadata-syntax-for-github-actions#runs-for-composite-actions
#   - https://docs.github.com/en/actions/sharing-automations/creating-actions/creating-a-composite-action
# requirements:
# - ACTIONS_AMAZON_ECR_LOGIN_VERSION set in .env.tool-versions
# - setting up aws credentials prior to running this action:
#   - ./.github/actions/setup/aws/credentials
name: setup-aws-ecr-login
description: |
  ecrにログインする
inputs:
  registries:
    description: |
      - ecr private registryに紐付くAWSアカウントID一覧
      - comma-delimited list
      - ref:https://github.com/aws-actions/amazon-ecr-login/blob/main/action.yml#L18
    required: false
    default: ""
runs:
  using: composite
  steps:
    - name: source .env.tool-versions
      uses: ./.github/actions/setup/common/source-env-tool-versions
    # ref: https://github.com/aws-actions/amazon-ecr-login
    - name: login to ecr
      uses:
        "aws-actions/amazon-ecr-login@\
        ${{ env.ACTIONS_AMAZON_ECR_LOGIN_VERSION }}"
      with:
        http-proxy: false
        mask-password: true
        registries: ${{ inputs.registries }}
        registry-type: private
        skip-logout: false
