
# eslint-disable yml/block-mapping-colon-indicator-newline
# yaml-language-server: $schema=https://json.schemastore.org/github-action.json
# refs:
# - composite actions:
#   - https://docs.github.com/en/actions/sharing-automations/creating-actions/metadata-syntax-for-github-actions#runs-for-composite-actions
#   - https://docs.github.com/en/actions/sharing-automations/creating-actions/creating-a-composite-action
# requirements:
# WIP
name: release-please
description: |
  release please
runs:
  using: composite
  steps:
    # ref: https://github.com/actions/create-github-app-token
    - uses:
        "actions/create-github-app-token@\
        ${{ env.ACTIONS_CREATE_GITHUB_APP_TOKEN }}"
      id: app-token
      with:
        app-id: ${{ vars.INSTALLATION_ACCESS_TOKEN_APP_ID }}
        private-key: ${{ secrets.INSTALLATION_ACCESS_TOKEN_PRIVATE_KEY }}
    # ref: https://github.com/googleapis/release-please-action
    - uses:
        "googleapis/release-please-action@\
        ${{ env.ACTIONS_RELEASE_PLEASE }}"
      with:
        token: ${{ steps.app-token.outputs.token }}
