# yaml-language-server: $schema=https://json.schemastore.org/github-action.json
# refs:
# - composite actions:
#   - https://docs.github.com/en/actions/sharing-automations/creating-actions/metadata-syntax-for-github-actions#runs-for-composite-actions
#   - https://docs.github.com/en/actions/sharing-automations/creating-actions/creating-a-composite-action
name: source-github-actions-repository-variables
description: |
  GitHub Actions Repository Variablesを全てGITHUB_ENVに出力する
inputs:
  GH_TOKEN:
    description: |
      GitHub Token
    required: false
    default: ${{ github.token }}
runs:
  using: composite
  steps:
    # ref: https://github.com/actions/create-github-app-token
    - name: append GitHub Actions Repository Variables to GITHUB_ENV
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.GH_TOKEN }}
      run: |
        gh api repos/${{ github.repository }}/actions/variables --jq '.variables[] | "\(.name)=\(.value)"'>>"${GITHUB_ENV}"
