# yaml-language-server: $schema=https://json.schemastore.org/github-action.json
name: setup-pytest
description: |
  pytestのセットアップを行う
runs:
  using: composite
  steps:
    - name: setup python
      uses: ./.github/actions/setup/python
    - name: install pytest
      shell: bash
      run: "pip install pytest==${PYTEST_VERSION}"
    - name: cache pytest
      uses: actions/cache@v4.0.2
      with:
        path: .pytest_cache
        key: "${{ runner.os }}-\
          pytest-\
          cache-\
          ${{ github.sha }}"
        restore-keys: "${{ runner.os }}-\
          pytest-\
          cache-"
