name: 001_ci_app_python
run-name: ci_app_python
on:
  pull_request:
    branches:
      - dev
      - test
      - stg
      - prod
    paths:
      - "**/*.py"
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
  workflow_dispatch: {}
permissions:
  id-token: write
  pull-requests: write
  contents: read
jobs:
  ci:
    secrets: inherit
    uses: ./.github/workflows/template_ci_app_python.yml
