name: poc
run-name: poc
on:
  # push:
  #   branches:
  #     - main # only trigger that works with release-please
  workflow_dispatch: {}
permissions:
  id-token: write
  pull-requests: write
  contents: write
jobs:
  poc:
    runs-on: ubuntu-24.04
    steps:
      - name: checkout
        # ref: https://github.com/actions/checkout
        uses: actions/checkout@v4.1.1
      - name: github app token
        # ref: https://github.com/actions/create-github-app-token
        uses: actions/create-github-app-token@v1.11.0
        id: app-token
        with:
          app-id: ${{ vars.INSTALLATION_ACCESS_TOKEN_APP_ID }}
          private-key: ${{ secrets.INSTALLATION_ACCESS_TOKEN_PRIVATE_KEY }}
      - name: source GitHub Actions Repository Variables
        uses: ./.github/actions/setup/common/source-github-actions-repository-variables
        with:
          GH_TOKEN: ${{ steps.app-token.outputs.token }}
      # ref: https://github.com/googleapis/release-please-action
      - uses: googleapis/release-please-action@v4.1.3
        with:
          token: ${{ steps.app-token.outputs.token }}
